### ISSUE TITLE
muchsync Mac OS X incompatibilities

### ISSUE THREAD

**Issue by stanford-scs** [johnnyutahh/search-based-email#2]
You mention problems getting muchsync compiled on Mac OS X.  These problems shouldn't be that hard to resolve.  Can you check the following release candidate and let me know if it fixes the problem, or if not what the remaining issues are.  I'd like to put out a new release that works on OS X, but I don't have access to the platform myself.

http://www.muchsync.org/src/muchsync-2rc1.tar.gz

**Comment by johnnyutahh** [comment]
Thanks for following up on this, quite helpful. Here's a log of the 
(seemingly) failed build attempt on my Mac OS 10.9.5 machine: 
https://gist.github.com/johnnyutahh/6e2316b051de19faee7c

Does this provide what you need for the next iteration? If not, please 
let me know what else I can do or provide.

Thanks again.

**Comment by johnnyutahh** [comment]
I should also note: I'm happy to retry the make/build as often as needed to help assist with the port. So please don't be shy about asking for a make retry.

**Comment by stanford-scs** [comment]
Ah, okay.  So there are a couple of other functions that need to be fixed like this.  Let me give that a a shot.  It might be simplest to debug via email, you want to mail me.

**Comment by johnnyutahh** [comment]
Hi Professor Mazières,

Please let me know what I can do to help with the Mac OS X muchsync 
port. (My github avatar = Johnny Utahh.)

Thanks,
Matt

On 8/16/15, 6:51 PM, stanford-scs wrote:
>
> Ah, okay. So there are a couple of other functions that need to be 
> fixed like this. Let me give that a a shot. It might be simplest to 
> debug via email, you want to mail me at: 
> mazieres-tzkdqff9rh44wihsvbd2uhtcjs@ta.scs.stanford.edu 
> <mailto:mazieres-tzkdqff9rh44wihsvbd2uhtcjs@ta.scs.stanford.edu>
>
> ---
> Reply to this email directly or view it on GitHub 
> <https://github.com/johnnyutahh/search-based-email/issues/2#issuecomment-131637534>.
>



-- 
//

**Comment by stanford-scs** [comment]
The Mac OS X build problems should be fixed in muchsync version 2.

**Comment by johnnyutahh** [comment]
Proof of muchsync-2 build on Mac OS 10.9.5:
https://gist.github.com/johnnyutahh/da30ee5ae1a5fd27cf90
